### ISSUE TITLE
Add support for verifying SignatureInfo structures.

### ISSUE THREAD

**Issue by fotisl** [PeculiarVentures/PKI.js#143]
Hi @YuryStrozhevsky,
can you add support for verifying SignatureInfo structures? This would be useful when validating RFC2985 counter signatures. Furthermore, I think it will not be that difficult, since most of the code is already written for the SignedData verification. You could even transfer the code from SignedData to SignatureInfo, and then use the signer parameter of SignedData.verify() to call the appropriate SignatureInfo.verify().

**Comment by YuryStrozhevsky** [comment]
@fotisl I do not like the idea because SignatureInfo has no necessary data for validation. I mean SignedData has all these necessary attributes/data:

1. digestAlgorithms
2. encapContentInfo
3. certificates
4. crls

In fact SignatureInfo has only signed/unsigned attributes and signature itself. Thus better to get small amount of data from SignatureInfo in scope of SignedData "verify" function than put all SignedData data to SignatureInfo "verify" function.

In order to verify countersignatures you would need to implement your routines - PKIjs has no support for it since it is too specific and could be more or less easily implemented by developers using existing PKIjs types.
