### ISSUE TITLE
how to verify a certificate file with domain name?

### ISSUE THREAD

**Issue by hiepnm** [PeculiarVentures/PKI.js#144]
I have a certificate file (a string), and a domain name example "example.com".
How to write a function like this.
`function verify(cert_string, domain);`
return a boolean value
true: if cert_string is for domain
false: if not

**Comment by rmhrisk** [comment]
@hiepnm PKIjs was designed as a generalized certificate validation library and does not currently provide a TLS certificate policy validation module.

You can, however, implement this check with PKIjs,  according to RFC 6125, the validator must check SAN first, and if SAN exists, then CN should not be checked. 

This is a technically correct way to do the checking of the CN value but may have some compatibility issues if dealing with poorly constructed certificates. Some more reading on this can be found in this post: http://unmitigatedrisk.com/?p=381

Additionally, you may need to support wildcard certificates; a wildcard certificate contains an asterisk (*) in the left-most position of any of the Subject fully qualified Domain Names contained in the Certificate.

Your logic for your verify(cert,domain) would look something like:
1. Makes sure the domain is a fully qualified domain
2. If a SAN extension is present, for each dnsName that contains a fully qualified domain name compare the domain to dnsName values in the SAN
3. If a SAN extension is not present, for each CN that contains a fully qualified domain name compare the domain to CN

In general, you should probably review the Chrome and Firefox equivalent logic and mirror what they do.

If you do this we would appreciate a sample function back we could review, provide feedback on and point others at in the future if they have a similar need.

Useful reading: http://crypto.stanford.edu/~dabo/pubs/abstracts/ssl-client-bugs.html

**Comment by YuryStrozhevsky** [comment]
@rmhrisk In fact you are not 100% correct - PKIjs could make such validation and it was designed from the very beginning. There are a set of specialized parameters for CertificateChainValidationEngine class and one of them is "initialPermittedSubtreesSet". By using it user could validate that each certificate in the chain has permitted domain name (or RFC822 name, or "directoryName", or URI name, or IP address). Moreover, there is another parameter "initialRequiredNameForms" where user could request types for names inside whole certificate chain.

At the moment I do not have example how to use it and would prepare it when have a time. @hiepnm

**Comment by rmhrisk** [comment]
Happy to be wrong.

**Comment by YuryStrozhevsky** [comment]
@hiepnm In found that in fact PKIjs already has an example code of what you requested. The example is [NIST PKITS example](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/NISTPKITS). In this PKIjs we show that PKIjs could successfully validate against all test data from NIST PKI Test Suite (NIST PKITS). Here is the [test with valid DNS name](https://github.com/PeculiarVentures/PKI.js/blob/master/examples/NISTPKITS/es6.js#L4678) (related NIST PKITS test number is 4.13.30)and here is the [test with invalid DNS name](https://github.com/PeculiarVentures/PKI.js/blob/master/examples/NISTPKITS/es6.js#L4693) (related NIST PKITS test numbr is 4.13.31). 

So, PKIjs could validate end-user certificate by DNS name but in fact it is not a function of validating for just one certificate - in order to validate it PKIjs would need a full "certificate chain". Also at the moment I do not have an explicit example with "initialPermittedSubtreesSet" but do hope would be not so difficult to understand how to use it analyzing the existing examples I early mentioned. Please let me know your opinion.

**Comment by hiepnm** [comment]
@YuryStrozhevsky Thank you very much. I will try it. I look it so difficult. I only want to write a simple validating function with a specific domain name (no wildcard).

**Comment by YuryStrozhevsky** [comment]
@hiepnm In the way I mentioned is looks too difficult for you then I propose you to implement your own function validating Subject Alternative Name (SAN) certificate extension. As an example you could looks for "function compareDNSName(name, constraint) ..." inside "pkijs/src/CertificateChainValidationEngine.js" file.
