### ISSUE TITLE
Unresolved Dependency 

### ISSUE THREAD

**Issue by sanaullah82** [PeculiarVentures/PKI.js#157]
I am trying to build the project using 
npm install
npm run build:examples

but getting unresolved dependencies.  

es6.js → ../../test/nodePKCS12Example.js...
(!) Unresolved dependencies
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
crypto (imported by NodeEngineNodeSpecific.js, commonjs-external:crypto)
(!) Circular dependency: ../../src/common.js -> ../../src/CryptoEngine.js -> ../../src/common.js
(!) Circular dependency: ../../src/common.js -> ../../src/CryptoEngine.js -> ../../src/PublicKeyInfo.js -> ../../src/common.js
(!) Circular dependency: ../../src/SafeContents.js -> ../../src/SafeBag.js -> ../../src/SafeContents.js
created ../../test/nodePKCS12Example.js in 12.1s

I am also new with ES6 based code and i don't know how to start the nodePKCS12Example.js example. can you please let me know how to start it ?

**Comment by YuryStrozhevsky** [comment]
@sanaullah82 The reason of this "unresolved dependency" is that in `NodeEngineNodeSpecific.js` I have 
```javascript
const crypto = require("crypto");
```

And during making bundle Rollup can not physically resolve Node internal module `crypto` and thus put in output bundle this code:
```javascript
var crypto = _interopDefault(require('crypto'));
```
Since the `NodePKCS12Example` intended to be using **in Node.js evironment ONLY** this would not lead to any problem - the `crypto` variable woul be initialized correctly.

So, if you are trying to use PKCS12 in browser better for you would be to check [this example](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/PKCS12SimpleExample).

**Comment by YuryStrozhevsky** [comment]
As for "how to start nodePKCS12Example.js" - in fact this example was intended to run using Mocha. So, you could run it by
```
mocha <path_to_nodePKCS12Example.js>
```

**Comment by YuryStrozhevsky** [comment]
As for your [issue to jsrsasign](https://github.com/kjur/jsrsasign/issues/330):

> pkijs support ECC keys too but the generated p12 file are encrypted with stronger ciphers like AES-GCM or AES-CBC where as Windows only support 3DES based p12 encrypted files.

In fact the `NodePKCS12Example` code produces correctly recognized by Windows PKCS12 files. But again - this example is for Node.js environment only and you could not run it in browser. And inside browser PKCS12 example there is not possibility (at least using default crypto engine) to have 3DES just because PKIjs is using WebCrypto API in which we do not have 3DES support.

**Comment by sanaullah82** [comment]
Thanks Yury.
how about generating the ECC keys using pkijs and then creating the pkcs12 with forge https://github.com/digitalbazaar/forge. but here the problem is pkijs only support RSA

**Comment by YuryStrozhevsky** [comment]
@sanaullah82 In fact I do not see any problems to do all this using PKIjs only. But, of course, it would lead to modifications of existing examples and probably writing specific crypto engine. All remaining work is up to you.

**Comment by sanaullah82** [comment]
@YuryStrozhevsky can you provide me some more details on writing specific crypto engine ? or i can include some already exiting one ?

**Comment by YuryStrozhevsky** [comment]
@sanaullah82 In fact in `NodePKCS12Example` you can find example of specific crypto engine - `NodeEngine.js`. And by default PKIjs is using [this crypto engine](https://github.com/PeculiarVentures/PKI.js/blob/master/src/CryptoEngine.js). You could use these two files as an example.

**Comment by sanaullah82** [comment]
@YuryStrozhevsky I have complied the  NodePKCS12Example but its dependent on node-webcrypto-ossl which is used openssl, as i am looking the crypto engine to support 3DES to generate windows supported p12 file on client side, do you think its going to help  or should i have to integrate some other crypto engine too?

**Comment by rmhrisk** [comment]
https://github.com/openpgpjs/openpgpjs/issues/416 Contains a JavaScript 3DES.
