### ISSUE TITLE
Can't add SAN to CSR attributes

### ISSUE THREAD

**Issue by mourkeita** [PeculiarVentures/PKI.js#166]
Hello,

Im using pkijs but i have some issues when i try to add SAN to my CSR.

Here is a snippet that i'm using to generate CSR attributes: and it does not work
pkcs10.attributes.push(new Attribute({
type: "1.2.840.113549.1.9.14", // pkcs-9-at-extensionRequest
values: [new Extensions({
extensions: [new Extension({
extnID: "2.5.29.17",
critical: false,
extnValue: new Utf8String({value : "test"}).toBER(false)
})]
}).toSchema()]
}));

can you help me please ?

Thanks :)

**Comment by YuryStrozhevsky** [comment]
How did you find “it does not work”?

**Comment by mourkeita** [comment]
with an online CSR decoder https://www.sslchecker.com/csr/decode it shows weird characters before SANs.
Example: i just gave test.fr it shows   **.H**DNS:test.com

**Comment by YuryStrozhevsky** [comment]
You know I am too tired with all these stupid issues about SANs usage in pkijs. So I decided to update existing PKCS10 example with SANs. I will do this at my morning.

**Comment by YuryStrozhevsky** [comment]
@mourkeita I have updates [PKCS#10 Complex Example](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/PKCS10ComplexExample) with SAN. You could check how properly add it using correct PKI data structures.

Also I should say that [www.sslchecker.com](www.sslchecker.com) service working unproperly with SAN - it could not recognize correctly encoded data. So, in order to correctly check PKCS#10 use this OpenSSL command:
```console
openssl req -in csr.csr -text -noout
```

**Comment by mourkeita** [comment]
Thanks for your response @YuryStrozhevsky
