### ISSUE TITLE
AttributeTypeAndValue.isEqual() fails after values have been serialized

### ISSUE THREAD

**Issue by gnarea** [PeculiarVentures/PKI.js#234]
If you have two equivalent instances of `AttributeTypeAndValue`, `.isEqual()` works as expected unless one of the instances has been deserialized from a buffer.

Here's how to reproduce this:

```js
const assert = require('assert');
const asn1js = require('asn1js');
const pkijs = require('pkijs');

const attr1 = new pkijs.AttributeTypeAndValue({
  type: '2.5.4.3',
  value: new asn1js.BmpString({ value: 'Foo' })
});
const attr2 = new pkijs.AttributeTypeAndValue({
  type: '2.5.4.3',
  value: new asn1js.BmpString({ value: 'Foo' })
});
assert(attr1.isEqual(attr2)); // OK
assert(attr2.isEqual(attr1)); // OK

const attrSerialized = attr1.toSchema().toBER(false);
const schema = asn1js.fromBER(attrSerialized).result;
const attrDeserialized = new pkijs.AttributeTypeAndValue({ schema });
assert(attrDeserialized.isEqual(attr1)); // Not OK
assert(attr1.isEqual(attrDeserialized)); // Not OK
```

For some reason I can't figure out, the following evaluates to `false` even though it should definitely be `true`:

https://github.com/PeculiarVentures/PKI.js/blob/682ef8d148e03adc4d7fe5ea1a0cdce4294f5e38/src/AttributeTypeAndValue.js#L173

So it's ultimately this line what ends up checking the equivalence of the two values, which fails because `attr1.value.valueBeforeDecode` is an `ArrayBuffer` of 8 bytes but `attrDeserialized.value.valueBeforeDecode` is an empty `ArrayBuffer`:

https://github.com/PeculiarVentures/PKI.js/blob/682ef8d148e03adc4d7fe5ea1a0cdce4294f5e38/src/AttributeTypeAndValue.js#L193

Is this really a bug or am I doing something wrong?

**Comment by YuryStrozhevsky** [comment]
@gnarea The problem here is not directly in PKI.js, but is a "nature of JavaScript". You have included `require('asn1js')` in your main file. But you need to aware that PKI.js also uses `asn1.js`, and in fact it would be **another** package due to different changes in NPM packaging structure. And thus when you are trying to compare `instanceof` you are comparing **different** instances, not same. I already had same issues in a number of my projects and first of all was trying to use exactly the same packages as PKI.js internally uses. But much better way is not to use `instanceof` at all. 

In the proposed solution I have removed all `instanceof` from particular function. Hope it would solve your problems.

**Comment by gnarea** [comment]
Thanks @YuryStrozhevsky! I just tested my code against the new release of PKI.js and it now works! :tada:
