### ISSUE TITLE
Read privateKey, publickey and x509 cert from .p12 file

### ISSUE THREAD

**Issue by almacenero** [PeculiarVentures/PKI.js#274]
Please add any example for read all parameters necesary for extract privateKey, publickey and x509 cert to pass to xades-bes library. All these from a .p12 token with password security

**Comment by YuryStrozhevsky** [comment]
1. [**Example 1**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/PKCS12SimpleExample)
2. [**Example 2**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/NodePKCS12Example)
3. [**Example 3**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/CertificateComplexExample)

Be aware that due to lack of 3-DES algorithm in WebCrypto API it is not possible to use common *.p12 files in browser, full *.p12 support only on Node.js evironment.

**Comment by rmhrisk** [comment]
> 1. [**Example 1**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/PKCS12SimpleExample)
> 2. [**Example 2**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/NodePKCS12Example)
> 3. [**Example 3**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/CertificateComplexExample)
> 
> Be aware that due to lack of 3-DES algorithm in WebCrypto API it is not possible to use common *.p12 files in browser, full *.p12 support only on Node.js evironment.

You can use webcrypto-liner In browser which has 3DES. You will have to add a custom engine.
