### ISSUE TITLE
Multiple Signatures PDF Modification

### ISSUE THREAD

**Issue by jmtiong** [PeculiarVentures/PKI.js#298]
I am attempting to implement multiple signatures on a PDF in my application. I read through the [adobe docs](https://www.adobe.com/devnet-docs/etk_deprecated/tools/DigSig/Acrobat_DigitalSignatures_in_PDF.pdf) and on `6.3.6  Multiple signatures` it has this image
<img width="329" alt="image" src="https://user-images.githubusercontent.com/16659123/100549405-bd348980-32ad-11eb-8b81-493b8f82c8ef.png">

I have successfully implement a single signer but now I am wondering how can I do it for multiple signers?

I saw [stackoverflow](https://stackoverflow.com/questions/33264784/multiple-signatures-invalidate-first-signature-in-itextsharp-pdf-signing) solution for itext stating to make it into `append mode` but I have no clue how it is done using this library.

Can anyone show me reference to how it can be implemented?

**Comment by rmhrisk** [comment]
PKI.js does not have anything to do with the PDF format we simple provided an example of embedding a CMS into a PDF to show an example of a use case for CMS, similar to how we did with SMIME.

We have another library we built when we made Hancock.ink to support the many different PDF use cases but it is not publicly available at this time.

Since this issue isn’t related to PKI.js I am closing the issue.
